AppTestGit/Controllers/CANDIDATsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AppTestGit;

namespace AppTestGit.Controllers
{
    public class CANDIDATsController : Controller
    {
        private DatabaseLocalEntities db = new DatabaseLocalEntities();

        // GET: CANDIDATs
        public ActionResult Index()
        {
            return View(db.CANDIDAT.ToList());
        }

        // GET: CANDIDATs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CANDIDAT cANDIDAT = db.CANDIDAT.Find(id);
            if (cANDIDAT == null)
            {
                return HttpNotFound();
            }
            return View(cANDIDAT);
        }

        // GET: CANDIDATs/Create
        
        public ActionResult Create()
        {
            return View();
        }

        // POST: CANDIDATs/Create
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public ActionResult Create(CANDIDAT cANDIDAT)
        {
            if (ModelState.IsValid)

            {
                db.CANDIDAT.Add(cANDIDAT);
                //creation de repertoire
                string folderName = Server.MapPath("~/CV");
                //creation de sous-reperoitre avec le nom et le prenom du candidat
                string pathString = System.IO.Path.Combine(folderName, cANDIDAT.nom +" " + cANDIDAT.prénom);
                System.IO.Directory.CreateDirectory(pathString);
                cANDIDAT.CvFile.SaveAs(pathString);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cANDIDAT);

        }

        // GET: CANDIDATs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CANDIDAT cANDIDAT = db.CANDIDAT.Find(id);
            if (cANDIDAT == null)
            {
                return HttpNotFound();
            }
            return View(cANDIDAT);
        }

        // POST: CANDIDATs/Edit/5
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "matricule,nom,prénom,mail,telephone,niveau,experience,dernier_employeur,cv_employeur")] CANDIDAT cANDIDAT)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cANDIDAT).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cANDIDAT);
        }

        // GET: CANDIDATs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CANDIDAT cANDIDAT = db.CANDIDAT.Find(id);
            if (cANDIDAT == null)
            {
                return HttpNotFound();
            }
            return View(cANDIDAT);
        }

        // POST: CANDIDATs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CANDIDAT cANDIDAT = db.CANDIDAT.Find(id);
            db.CANDIDAT.Remove(cANDIDAT);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AppTestGit/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AppTestGit.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

AppTestGit/Views/CANDIDATs/Create.cshtml
@model AppTestGit.CANDIDAT

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "CANDIDATs", FormMethod.Post,new {id="FormCreate", enctype="multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CANDIDAT</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prénom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prénom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prénom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.mail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.mail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.mail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.telephone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.telephone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.telephone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.niveau, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.niveau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.niveau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.experience, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.experience, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.experience, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dernier_employeur, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dernier_employeur, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dernier_employeur, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.cv_employeur, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cv_employeur, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cv_employeur, "", new { @class = "text-danger" })
            </div>
        </div>*@
        <div class="form-group">
            @Html.LabelFor(Model => Model.CvFile, htmlAttributes: new { @class="control-label col-md-2"})
            <div class="col-md-10">
                <input type="file" name="CvFile" required/>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Envoyer la candidature" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AppTestGit/Views/CANDIDATs/Delete.cshtml
@model AppTestGit.CANDIDAT

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CANDIDAT</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prénom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prénom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.mail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.telephone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.telephone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.niveau)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.niveau)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.experience)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.experience)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dernier_employeur)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dernier_employeur)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cv_employeur)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cv_employeur)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AppTestGit/Views/CANDIDATs/Details.cshtml
@model AppTestGit.CANDIDAT

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>CANDIDAT</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prénom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prénom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.mail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.telephone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.telephone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.niveau)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.niveau)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.experience)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.experience)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dernier_employeur)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dernier_employeur)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cv_employeur)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cv_employeur)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.matricule }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AppTestGit/Views/CANDIDATs/Edit.cshtml
@model AppTestGit.CANDIDAT

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CANDIDAT</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.matricule)

        <div class="form-group">
            @Html.LabelFor(model => model.nom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prénom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prénom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prénom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.mail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.mail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.mail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.telephone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.telephone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.telephone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.niveau, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.niveau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.niveau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.experience, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.experience, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.experience, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dernier_employeur, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dernier_employeur, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dernier_employeur, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cv_employeur, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cv_employeur, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cv_employeur, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AppTestGit/Views/CANDIDATs/Index.cshtml
@model IEnumerable<AppTestGit.CANDIDAT>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table" id="candidat">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.nom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.prénom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.mail)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.telephone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.niveau)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.experience)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.dernier_employeur)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.cv_employeur)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.nom)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.prénom)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.mail)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.telephone)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.niveau)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.experience)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.dernier_employeur)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.cv_employeur)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.matricule }) |
                    @Html.ActionLink("Details", "Details", new { id = item.matricule }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.matricule })
                </td>
            </tr>
        }
    </tbody>
</table>
@section scripts
{
<script>
    $(document).ready(function () { $("#candidat").DataTable() })
</script>
}

AppTestGit/Views/Candidat.cshtml
@{
    ViewBag.Title = "Candidat";
}

<h2>Candidat</h2>

AppTestGit/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

AppTestGit/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AppTestGit/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

AppTestGit/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nom d'application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Accueil", "Index", "Home")</li>
                    <li>@Html.ActionLink("À propos de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mon application ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>